title: Where is the space station?
hero_image: images/banner.png
description: Plot the location of the international space station
version: 41
listed: false
copyedit: false
last_tested: "2024-06-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
